# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='dificultad',
            field=models.CharField(choices=[('B\xe1sica', 'B\xe1sica'), ('Intermedia', 'Intermedia'), ('Avanzada', 'Avanzada')], max_length=200),
        ),
    ]
