# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_auto_20170729_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
