# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombres',
            new_name='nombre1',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
