# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='C\xf3digo asignatura')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de asignatura')),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('creditos', models.IntegerField()),
                ('nivel', models.CharField(max_length=50, verbose_name='Per\xedodo')),
                ('caracter', models.CharField(blank=True, max_length=50, null=True)),
                ('horas_teoricas', models.IntegerField(blank=True, null=True)),
                ('horas_laboratorio', models.IntegerField(blank=True, null=True)),
                ('horas_teoricas_personal', models.IntegerField(blank=True, editable=False, null=True)),
                ('horas_laboratorio_personal', models.IntegerField(blank=True, editable=False, null=True)),
                ('horas_dedicadas', models.IntegerField(blank=True, editable=False, null=True)),
                ('programas_academicos', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_requisitos', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_requisito', models.CharField(blank=True, max_length=100, null=True)),
                ('co_requisitos', models.CharField(blank=True, max_length=50, null=True)),
                ('equivalencias', models.CharField(blank=True, max_length=50, null=True)),
                ('eje_curricular', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('disponible', models.BooleanField(default=True)),
                ('tipo_programa', models.CharField(choices=[('Regular', 'Regular'), ('Advance', 'Advance')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_biblio', models.CharField(choices=[('Obligatoria', 'Obligatoria'), ('Complementaria', 'Complementaria'), ('Linea', 'Recursos en l\xednea')], max_length=50, verbose_name='Tipo de bibliograf\xeda')),
                ('bibliografia', models.TextField(verbose_name='Bibliograf\xeda')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionesAprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_condicion', models.TextField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150)),
                ('aprendizaje_esperado', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrc', models.CharField(max_length=50)),
                ('regimen', models.CharField(max_length=200)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.PerfilUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(default='Ingenieria', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos_educacionales', models.TextField(blank=True, null=True, verbose_name='Objetivos educacionales')),
                ('competencias_egreso', models.TextField(blank=True, null=True, verbose_name='Competencias de egreso')),
                ('aprendizaje', models.TextField(blank=True, null=True, verbose_name='Resultados de aprendizaje')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n general')),
                ('habilidades', models.TextField(blank=True, null=True, verbose_name='Habilidades transversales')),
                ('modalidad', models.TextField(blank=True, null=True, verbose_name='Modalidad did\xe1ctica y procedimientos de evaluaciones')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura', verbose_name='Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(default='Antonio Varas', max_length=255)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('unidad', models.IntegerField(null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura', verbose_name='Asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Unidad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Facultad'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Sede'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Carrera'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='coordinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.PerfilUsuario'),
        ),
    ]
