# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_curso_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
