# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0003_curso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='aprendizaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
