# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0004_unidad_aprendizaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='codigo_carrera',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
