# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0005_carrera_codigo_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_egreso', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadTransversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad_transversal', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadDidactica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad_didactica', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEducacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_educacional', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_aprendizaje', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Asignatura')),
            ],
        ),
        migrations.RemoveField(
            model_name='informacion',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='facultad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Informacion',
        ),
    ]
