# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntas', '0005_auto_20170729_0345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_auto_20170728_2115'),
        ('contenidos', '0003_curso_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('puntaje_obtenido', models.FloatField(blank=True, null=True)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Calificacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('puntaje_total', models.IntegerField(blank=True, null=True)),
                ('exigencia', models.IntegerField(blank=True, null=True)),
                ('tipo_evaluacion', models.CharField(blank=True, choices=[('Solemne', 'Solemne'), ('Control', 'Control'), ('Examen', 'Examen'), ('Otro', 'Otro')], max_length=200, null=True)),
                ('tipo_evaluacion_otro', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('datos', models.TextField(blank=True, null=True)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('disponible', models.BooleanField(default=False)),
                ('contenidos', models.ManyToManyField(blank=True, to='contenidos.Unidad')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenidos.Curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preguntas', models.ManyToManyField(blank=True, to='preguntas.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Promedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.FloatField()),
                ('pje_promedio', models.FloatField(blank=True, null=True)),
                ('calificaciones', models.ManyToManyField(to='evaluacion.Calificacion')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenidos.Curso')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='PuntajePregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Evaluacion')),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='estudiantecalificacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Evaluacion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.Evaluacion'),
        ),
    ]
