# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_evaluacion_descartada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='cronometro_inicio',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
